module.exports = {
    DEFAULT_TOTAL_SETS: 3,
    DEFAULT_READY: 10,
    DEFAULT_ACTION: 70,
    DEFAULT_REST: 20,
    DEFAULT_REST_SET: 180,

    WARMUP_COUNTDOWN: 100,
    MUSIC: [
        require('../assets/music/1.mp3'),
        require('../assets/music/2.mp3'),
        require('../assets/music/3.mp3'),
        require('../assets/music/4.mp3'),
        require('../assets/music/5.mp3'),
        require('../assets/music/6.mp3'),
        require('../assets/music/7.mp3'),
        require('../assets/music/8.mp3'),
        require('../assets/music/9.mp3'),
        require('../assets/music/10.mp3'),
        require('../assets/music/11.mp3'),
        require('../assets/music/12.mp3'),
        require('../assets/music/13.mp3'),
        require('../assets/music/14.mp3'),
        require('../assets/music/15.mp3'),
        require('../assets/music/16.mp3'),
        require('../assets/music/17.mp3'),
        require('../assets/music/18.mp3'),
        require('../assets/music/19.mp3'),
        require('../assets/music/20.mp3'),
        require('../assets/music/21.mp3'),
        require('../assets/music/22.mp3'),
        require('../assets/music/23.mp3'),
        require('../assets/music/24.mp3'),
        require('../assets/music/25.mp3'),
        require('../assets/music/26.mp3'),
        require('../assets/music/27.mp3'),
        require('../assets/music/28.mp3'),
        require('../assets/music/29.mp3'),
        require('../assets/music/30.mp3'),
        require('../assets/music/31.mp3'),
        require('../assets/music/32.mp3'),
        require('../assets/music/33.mp3'),
        require('../assets/music/34.mp3'),
        require('../assets/music/35.mp3'),
        require('../assets/music/36.mp3'),
        require('../assets/music/37.mp3'),
        require('../assets/music/38.mp3'),
        require('../assets/music/39.mp3'),
        require('../assets/music/40.mp3'),
        require('../assets/music/41.mp3'),
        require('../assets/music/42.mp3'),
        require('../assets/music/43.mp3'),
        require('../assets/music/44.mp3'),
        require('../assets/music/45.mp3'),
        require('../assets/music/46.mp3'),
        require('../assets/music/47.mp3'),
        require('../assets/music/48.mp3'),
        require('../assets/music/49.mp3'),
        require('../assets/music/50.mp3'),
        require('../assets/music/51.mp3'),
        require('../assets/music/52.mp3'),
        require('../assets/music/53.mp3'),
        require('../assets/music/54.mp3'),
    ],
    MUSIC_NUM: 54,

    AWS_DYNAMODB_REGION: 'ap_northeast_1',
    AWS_COGNITO_IDENTITY_POOL_ID: 'ap-northeast-1_iNKGIoFVd',
    AWS_COGNITO_APP_CLIENT_ID: '7lhlkkfbfb4q5kpp90urffao',
}
